version: "3.4"

services:
  # The BuildStream builder, and image to work in
  builder:
    build:
      context: .
      target: builder
    command: bash -c "while true; do sleep 3000; done;"
    privileged: true

    environment:
      INTEGRATION_CACHE: /home/buildstream/.cache/bst-integration-cache

    networks:
      - caches
      - remote-execution

    volumes:
      - type: bind
        source: ./
        target: /home/buildstream/workspace
        consistency: cached
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: builder_cache
        target: /home/buildstream/.cache

    devices:
      - /dev/fuse

  # Cache for sources that the BuildStream client downloads
  bst-source-cache:
    build:
      context: .
      target: artifact_server

    command: bst-artifact-server --enable-push -p 8000 /home/buildstream/cache

    networks:
      - caches

    volumes:
      - type: volume
        source: source_cache
        target: /home/buildstream/cache


  # Cache for artifacts that the BuildStream client builds
  bst-artifact-cache:
    build:
      context: .
      target: artifact_server

    command: bst-artifact-server --enable-push -p 8000 /home/buildstream/cache

    networks:
      - caches

    volumes:
      - type: volume
        source: artifact_cache
        target: /home/buildstream/cache

  # Remote Execution server
  buildgrid:
    build:
      context: .
      target: buildgrid

    command: bgd server start /home/buildgrid/buildgrid.conf -vvv

    networks:
      - remote-execution

  buildbox-worker:
    build:
      context: .
      target: buildbox_worker

    privileged: true

    command: supervisord --configuration /home/buildgrid/supervisord.conf

    depends_on:
      - buildgrid

    networks:
      - remote-execution


networks:
  caches:
  remote-execution:


volumes:
  artifact_cache:
  builder_cache:
  source_cache:
