version: "3.4"

services:
  builder:
    build: .
    command: bash -c "while true; do sleep 3000; done;"
    privileged: true

    environment:
      INTEGRATION_CACHE: /home/buildstream/.cache/bst-integration-cache

    volumes:
      - type: bind
        source: ./
        target: /home/buildstream/workspace
        consistency: cached
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: builder_cache
        target: /home/buildstream/.cache

    devices:
      - /dev/fuse


volumes:
  builder_cache:
